In [1]:
"""
This is the example to execute 
the Robot_Metalico
@author olmerg
"""
import sys  
sys.path.append( 'Robot_Metalico')
sys.path.append( '../../Swift_serial')
import numpy as np
import roboticstoolbox as rtb
from RobotMetalico import RobotMetalico
from Swift_serial import Swift_serial
from math import pi

if __name__ == '__main__':   # pragma nocover

    env = Swift_serial('COM9',115200)
    robot=RobotMetalico()
    print(robot)
    print(robot.to_dict)
    # the robot should start in home 
    env.launch()
    env.add(robot)    
#------------------------------------------------------------------------------------------------------------------------
    Tray1 = rtb.tools.trajectory.jtraj([0, 0, 0, 0, 0],[0, (2*pi/9), (2*pi/9), (-pi/3), 0],50)
    Tray2 = rtb.tools.trajectory.jtraj([0, (2*pi/9), (2*pi/9), (-pi/3), 0],[pi/2, (2*pi/9), (2*pi/9), (pi/3), 0],50)  
    Tray3 = rtb.tools.trajectory.jtraj([pi/2, (2*pi/9), (2*pi/9), (pi/3), 0],[0, 0, 0, 0, 0],50) 
    Tray4 = rtb.tools.trajectory.jtraj([0, 0, 0, 0, 0],[0, (2*pi/9), (2*pi/9), (-pi/3), 0],50)  
    Tray5 = rtb.tools.trajectory.jtraj([0, (2*pi/9), (2*pi/9), (-pi/3), 0],[-pi/2, (2*pi/9), (2*pi/9), (pi/3), 0],50) 
#------------------------------------------------------------------------------------------------------------------------    

#----------------------------
    for q in Tray1.y:
         #print(q)
         robot.q=q
         env.step(0.1)
#----------------------------
    for q in Tray2.y:
         #print(q)
         robot.q=q
         env.step(0.1)
#----------------------------
    for q in Tray3.y:
         #print(q)
         robot.q=q
         env.step(0.1)
#----------------------------
    for q in Tray4.y:
         #print(q)
         robot.q=q
         env.step(0.1)
#----------------------------
    for q in Tray5.y:
         #print(q)
         robot.q=q
         env.step(0.1)
#----------------------------

#----------------------------
    # return to home
    env.reset()
#----------------------------

init serial  COM9  speed  115200
┌───┬───────────┬───────────┬───────────────┬────────────────────────────────┐
│id │   link    │  parent   │     joint     │              ETS               │
├───┼───────────┼───────────┼───────────────┼────────────────────────────────┤
│ 0 │     world │         - │               │                                │
│ 1 │ base_link │     world │          Join │                                │
│ 2 │    link_1 │ base_link │       joint_1 │ tz(0.75) * Rz(q0)              │
│ 3 │    link_2 │    link_1 │       joint_2 │ tz(0.55) * Rz(89.95°) * Ry(q1) │
│ 4 │    link_3 │    link_2 │       joint_3 │ tz(1.2) * Ry(q2)               │
│ 5 │    link_4 │    link_3 │       joint_4 │ tz(1.0) * Ry(q3)               │
│ 6 │  @Gripper │    link_4 │ joint_Gripper │ tz(0.7) * Rz(89.95°) * Rz(q4)  │
└───┴───────────┴───────────┴───────────────┴────────────────────────────────┘

┌─────┬──────┬──────┬──────┬──────┬─────┐
│name │ q0   │ q1   │ q2   │ q3   │ q4  │
├─────┼──────

[-3. -2. -2. -2.  0.]
['0', '45', '98', '-42', '0', '90']
[-3. -2. -2. -2.  0.]
['0', '45', '98', '-42', '0', '90']
[-3. -2. -2. -2.  0.]
['0', '45', '98', '-42', '0', '90']
[-3. -2. -2. -2.  0.]
['0', '45', '98', '-42', '0', '90']
[-3. -1. -1. -2.  0.]
['0', '45', '98', '-42', '0', '90']
[-3. -1. -1. -2.  0.]
['0', '45', '98', '-42', '0', '90']
[-3. -1. -1. -2.  0.]
['0', '45', '98', '-42', '0', '90']
[-3. -1. -1. -2.  0.]
['0', '45', '98', '-41', '0', '90']
[-3. -1. -1. -2.  0.]
['0', '45', '98', '-41', '0', '90']
[-3. -1. -1. -2.  0.]
['2', '45', '98', '-39', '0', '90']
[-3. -1. -1. -2.  0.]
['3', '45', '98', '-38', '0', '90']
[-2. -1. -1. -2.  0.]
['4', '45', '98', '-36', '0', '90']
[-2. -1. -1. -1.  0.]
['5', '45', '98', '-34', '0', '90']
[-2. -1. -1. -1.  0.]
['7', '45', '98', '-33', '0', '90']
[-2. -1. -1. -1.  0.]
['7', '45', '98', '-33', '0', '90']
[-2. -1. -1. -1.  0.]
['11', '45', '98', '-31', '0', '90']
[-1. -1. -1. -1.  0.]
['13', '45', '98', '-30', '0', '90']
[-1. -1. -1.